### PR TITLE
Add working mobile nav-bar

### PR DESCRIPTION
**Pull request by sbernheim4**

### CODE REVIEW

**Comment by sbernheim4** [comment]
@bryancjones take a look and let me know if the UI is good. I'm going to add in some transitioning later so that it's not as jumpy when hovering over the options titles

**Comment by sbernheim4** [comment]
@ldthorne do you think it'd be better to use angular's animations or to use the mini jquery that angular comes with.

**Comment by bryancjones** [comment]
@sbernheim4 I like the design, but seems a little buggy. I see the jumpy UI, so we can address that later. 

The bigger issue is that when I open it on my phone I can only access the "What is Kinetic" drop down. The other items in the navbar do not open their drop-downs. However, when I shrink screen size on my computer, it's not an issue. Similarly, when I look at the deployment on my phone, it offsets the "Our Solution" section on the homepage (but not when I just shrink the window on my computer).

Lastly, when I make my phone landscape, it shows the full navbar now -- but it doesn't fully fit. Would it be possible to have the mobile navbar appear even with horizontal view on mobile? I think it would be simpler UI.

**Comment by sbernheim4** [comment]
@bryancjones can you attach some screenshots of what your describing. When I tested it on my phone it seemed to work as expected

**Comment by sbernheim4** [comment]
@bryancjones I realized, the nav-bar was working in safari before I made it more compact but when I made it more compact, it got thrown off since I guess safari doesn't support some of the css that I used to make it more compact. Should Do you want me to revert the nav-bar to before I made it more compact so that it is supported on safari. This should also then fix the issues of the mobile version

**Comment by bryancjones** [comment]
@sbernheim4 Got it, that makes sense. Yes, I think we should revert the navbar to how it was before. The expanded navbar should be less of an issue when we launch the mobile navbar because users will be able access everything even if they shrink their screen.

**Comment by bryancjones** [comment]
@sbernheim4 do you still need photos? I think we're on the same page for the navbar, but here is what I mean by offset. Also, the "Get the Kinetic Handbook Button" is cut off a little bit. It just might need smaller text because I think it has larger text than the rest of the buttons right now.

img_3300

img_3299

img_3301

**Comment by sbernheim4** [comment]
@bryancjones thanks those photos help a lot. What phone do you have?

**Comment by bryancjones** [comment]
@sbernheim4 I have an iPhone 6

**Comment by bryancjones** [comment]
@sbernheim4 The first photo (vertical view) is fixed now, but the second photo (horizontal view) is not.

**Comment by sbernheim4** [comment]
@bryancjones that section should now be fixed for landscape mode too. I'm still working on fixing the navbar for safari and building the mobile version.

**Comment by bryancjones** [comment]
@sbernheim4 Sounds good, thanks!

**Comment by sbernheim4** [comment]
@bryancjones The navbar should now be good in on desktop safari. I'm still looking into why some of the tabs won't dropdown on click for the mobile version. I should have that solved by the end of the day today

**Comment by sbernheim4** [comment]
@bryancjones The navbar is working correctly on my phone. Could you see if it is good on your iPhone

**Comment by bryancjones** [comment]
@sbernheim4 The drop-downs for Get Involved, Resources, and Our Team are still dead on my mobile navbar. Do you need to deploy it again?

**Pull request merged**
