### PR TITLE
Update buttons

### PR DESCRIPTION
**Pull request by ldthorne**
- [x] Update button styling
- [x] Remove donate button from landing page

### CODE REVIEW

**Comment by ldthorne** [comment]
@bryancjones take a look when you get a min

**Comment by bryancjones** [comment]
@ldthorne Thanks Daniel. Could we keep the Get Involved button filled in and link that to the Get Involved anchor on the home page?

**Comment by ldthorne** [comment]
@bryancjones take a look when you have a min. Seems a little weird to me to have one filled and the other transparent, but I also don't know a lot about design  ¯\\_(ツ)_/¯

**Comment by bryancjones** [comment]
@ldthorne Can we move them closer together? Medium has a good example of what we're going for. Essentially, the filled and transparent buttons are supposed to guide first-time visitors to the right place.

ex: https://medium.com/

**Comment by sbernheim4** [comment]
@bryancjones take a look now at this and let me know if this is good

**Comment by bryancjones** [comment]
@sbernheim4 Looks good to merge

**Pull request merged**
