### PR TITLE
Add overview video

### PR DESCRIPTION
**Pull request by ldthorne**
- [x] Add overview video
 - [x] Made mobile responsive 

Testers: Make sure to check if it works as expected on a mobile device (not just the mobile aspect ratio on your computer).

### CODE REVIEW

**Comment by bryancjones** [comment]
@ldthorne Looks good. Can we add an anchor for when you click on "What is Kinetic" in the navbar? So clicking the navbar takes you to the overview video anchor

**Comment by sbernheim4** [comment]
@bryancjones do you mean another link in the list or that if someone clicks on "What is Kinetic" it takes them to the video

**Comment by bryancjones** [comment]
@sbernheim4 Yes, it takes them to the Overview of Kinetic Global Text and shows the video embedded on the page (not taking them to the actual YouTube link)

**Comment by ldthorne** [comment]
hey all, sorry i've been MIA. @bryancjones my concern with making the `What is Kinetic` a link is that some people will click on it assuming that it will drop down the list, but will redirect them instead. Would making a row in the dropdown that says `Overview of Kinetic` or something like that?

**Comment by bryancjones** [comment]
@ldthorne I don't think we need to add an additional tab in the navbar. I was thinking that it made the most sense to make the navbar headers links. Like they are on this website: http://generationcitizen.org/. That said, if you think it makes more sense from a UI perspective to not have that navigation, then I don't think it's needed.

**Comment by ldthorne** [comment]
@bryancjones that sounds fine. i'm not sure if it's the most intuitive ui, but i also don't have a better suggestion. take a look at how it works now and let me know what you think!

**Comment by bryancjones** [comment]
@ldthorne This looks good. Let's push the deployment as you have. We can update it later if needed. Thanks!

**Comment by bryancjones** [comment]
@ldthorne Also, I will ask some people about it over the next week

**Comment by sbernheim4** [comment]
@bryancjones @ldthorne going to merge this in then

**Pull request merged**
