### PR TITLE
Build resource landing page

### PR DESCRIPTION
**Pull request by sbernheim4**

### CODE REVIEW

**Comment by sbernheim4** [comment]
@bryancjones https://kinetic-global-staging-pr-118.herokuapp.com/

**Comment by bryancjones** [comment]
@sbernheim4 Would it be possible to downsize everything a little bit? Boxes, picture, and text in the boxes?

**Comment by sbernheim4** [comment]
@bryancjones yes. Do you mean on mobile and on desktop or just one of them?

**Comment by bryancjones** [comment]
@sbernheim4 On both. The text looks a little tight on mobile, and everything would look cleaner if it were a little smaller on desktop. It switches to the mobile version too soon anyway because it doasn't fit unless it's a huge window.

**Comment by sbernheim4** [comment]
@bryancjones sure. I'll downsize everything

**Comment by bryancjones** [comment]
@sbernheim4 Looks good with the percents. 

However, on mobile, it's showing the navbar with the weird spacing again (not sure if that's on this PR or an artifact)

**Comment by sbernheim4** [comment]
@bryancjones can you attach a pic. My guess is its an artifact since this doesn't have any of the code from the nav-bar branch but it might be something that still exists

**Comment by bryancjones** [comment]
@sbernheim4 This is good to go live. The "Access Resources" button should now link here, and the "Resources" heading on the navbar should not link here.

**Pull request merged**
